"""
Error handlers for the RESTful app
Defines the responses which are generated by the application when there is an error
"""
import exc
from webargs import flaskparser
from marshmallow.exceptions import ValidationError
from flask import Flask, jsonify
from app.models.custom_error import CustomError
from app.schemas.custom_error import ErrorSchema

# Actual initialization of application. This happens here to prevent circular imports
app = Flask(__name__)

# Singleton object for marshalling response
error_schema = ErrorSchema()

##### Error Handlers #####

@app.errorhandler(404)
def page_not_found(error):
    """Override html 404 page with a json response"""
    response = CustomError("404_NOT_FOUND", error.description)
    return jsonify(error_schema.dump(response).data), 404

@app.errorhandler(405)
def method_not_allowed(error):
    """Override html 400 page with a json response"""
    response = CustomError("METHOD_NOT_ALLOWED", error.description)
    return jsonify(error_schema.dump(response).data), 405

@app.errorhandler(exc.UserNotFound)
def user_not_found(error):
    """
    Generic 404 type error for a user which can not be found
    Ambiguous whether setting does not ever exist or doesnt exist for particular user
    """
    response = CustomError("USER_NOT_FOUND", str(error))
    return jsonify(error_schema.dump(response).data), 404

@app.errorhandler(ValidationError)
def handle_bad_request(error):
    """This will Intercept the Validation Errors from Webargs"""
    response = CustomError("INPUT_VALIDATION_ERROR",
                       "One or more input parameter failed validation, see fields for more info",
                       fields=error.messages)
    return jsonify(error_schema.dump(response).data), 422

# This error handler is necessary for usage of webargs with Flask-RESTful
@flaskparser.parser.error_handler
def handle_request_parsing_error(error):
    """
    webargs error handler that raises validation error for flask handling
    see handle_bad_request for error handling
    """
    raise error


